name: Integration Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  mysql-tlog-tiles-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Start Docker services (tessera-conformance-mysql-db and tessera-conformance-mysql)
        run: docker compose -f ./cmd/conformance/mysql/docker/compose.yaml up --build --detach
      - name: Run integration test 
        run: go test -v -race ./integration/... --run_integration_test=true --log_url="http://localhost:2024" --write_log_url="http://localhost:2024" --log_public_key="transparency.dev/tessera/example+ae330e15+ASf4/L1zE859VqlfQgGzKy34l91Gl8W6wfwp+vKP62DW"
      - name: Stop Docker services (tessera-conformance-mysql-db and tessera-conformance-mysql)
        if: ${{ always() }}
        run: docker compose -f ./cmd/conformance/mysql/docker/compose.yaml down

  posix-tlog-tiles-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Start Docker services (tessera-conformance-posix)
        run: docker compose -f ./cmd/conformance/posix/docker/compose.yaml up --build --detach
      - name: Run integration test 
        run: go test -v -race ./integration/... --run_integration_test=true --log_url="file:///tmp/tessera-posix-log" --write_log_url="http://localhost:2025" --log_public_key="example.com/log/testdata+33d7b496+AeHTu4Q3hEIMHNqc6fASMsq3rKNx280NI+oO5xCFkkSx"
      - name: What's in the box?
        if: ${{ always() }}
        run: tree /tmp/tessera-posix-log
      - name: Stop Docker services (tessera-conformance-posix)
        if: ${{ always() }}
        run: docker compose -f ./cmd/conformance/posix/docker/compose.yaml down

  gcp-tlog-tiles-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Start Docker services (tessera-conformance-gcp, tessera-conformance-gcp-spanner and tessera-conformance-gcp-gcs)
        run: docker compose -f ./cmd/conformance/gcp/docker/compose.yaml up --build --detach
      - name: Run integration test 
        run: go test -v -race ./integration/... --run_integration_test=true
      - name: Stop Docker services (tessera-conformance-gcp, tessera-conformance-gcp-spanner and tessera-conformance-gcp-gcs)
        if: ${{ always() }}
        run: docker compose -f ./cmd/conformance/gcp/docker/compose.yaml down
